- name: CVE-2023-22518 Confluence Data Center and Server Improper Authorization Vulnerability Playbook
  gather_facts: false
  hosts: all
  vars:
    uri: "json/setup-restore.action"
    pattern1: 'The\szip\sfile\sdid\snot\scontain\san\sentry'
    pattern2: 'exportDescriptor\.properties'
    headers:
      content_type: 'multipart/form-data; boundary=----WebKitFormBoundaryT3yekvo0rGaL9QR7'
      atlassian_token: 'no-check'
  tasks:
    - name: Generate random fact
      ansible.builtin.set_fact:
        randomstr: "{{ lookup('community.general.random_string', length=12, special=false) }}"

    - name: Assess vulnerable condition
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}/{{ uri }}"
        method: POST
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
        headers:
          Content-Type: "{{ headers.content_type }}"
          X-Atlassian-Token: "{{ headers.atlassian_token }}"
        body_format: raw
        body: |
          ------WebKitFormBoundaryT3yekvo0rGaL9QR7
          Content-Disposition: form-data; name="buildIndex"

          false
          ------WebKitFormBoundaryT3yekvo0rGaL9QR7
          Content-Disposition: form-data; name="file";filename="{{ randomstr }}.zip"

          {{ randomstr }} 
          ------WebKitFormBoundaryT3yekvo0rGaL9QR7
          Content-Disposition: form-data; name="edit"

          Upload and import
          ------WebKitFormBoundaryT3yekvo0rGaL9QR7--
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Examine vulnerable condition response
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} is potentially vulnerable with response content: {{ response.content }}"
      when:
        - response is defined
        - response.status == 200
        - response.content | regex_search(pattern1)
        - response.content | regex_search(pattern2)
